@startuml
actor Usuario as usuario
boundary "Interfaz de Iniciar Sesion" as feIniciarSesion
usuario -right-> feIniciarSesion
control "Ingrese Usuario" as ingresarUsuario
control "Ingrese Contraseña" as ingresarContrasena
control "Validar datos" as validardatos

feIniciarSesion -down-> ingresarUsuario
feIniciarSesion-down-> ingresarContrasena
ingresarUsuario -down-> validardatos
ingresarContrasena -down-> validardatos
boundary "Mostrar Error" as mostrarerror
validardatos -down-> mostrarerror:Datos Incorrectos
control "Ingresar" as ingresar
validardatos-right->ingresar
usecase (Pagina Principal) as paginaprincipal
ingresar-down->paginaprincipal

@enduml
