@startuml
actor Usuario as usuario
control "Menú" as menu
control "Validar Informacion" as validarinformacion
usuario -right->menu
boundary "Consultas" as consultas
menu-right->consultas
boundary "Denuncias" as denuncias
consultas-down->denuncias
control "Ingresar Datos de Denuncia" as ingresardatosdenuncia
denuncias-right->ingresardatosdenuncia
control "Enviar Denuncia" as enviarDenuncia
boundary "Error" as error
ingresardatosdenuncia -down->validarinformacion
validarinformacion-down->error:Llene todos los campos.
validarinformacion-right-> enviarDenuncia
usecase (Pagina Principal) as paginaprincipal
enviarDenuncia-down->paginaprincipal
@enduml










@enduml
