@startuml
actor Usuario as usuario
control "Menú" as menu
boundary "Utilidades" as utilitarios
control "Seleccionar Beneficio" as seleccionarBeneficio
control "Ingresar Datos para Beneficio" as ingresardatosbeneficio
control "Validar Información" as validarinformacion
boundary "Error" as error
control "Enviar Solicitud de Beneficio" as enviarSolicitudBeneficio
usuario -right->menu
menu-down-> utilitarios
utilitarios -right-> seleccionarBeneficio
seleccionarBeneficio -down-> ingresardatosbeneficio
ingresardatosbeneficio -right-> validarinformacion
validarinformacion -down-> error: Llene todos los campos.
validarinformacion -right-> enviarSolicitudBeneficio
usecase (Pagina Principal) as paginaprincipal
enviarSolicitudBeneficio-down->paginaprincipal
@enduml
